version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: test
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: bank

    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/create-db.sql:ro
    networks:
      - bank-network

  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bank
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-db
    networks:
      - bank-network

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bank
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-db
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
