spring:
  datasource:
    url: jdbc:mysql://db:3306/banco?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  client-id: microclientes
  consumer-group-id: clientes-group

app:
  remote:
    account-service: http://account-service:8080/account
